#!/usr/bin/env bash

set -eu

(
  cd terraform
  terraform init
  terraform get
  terraform apply
)

ansible all -m ping

ansible-playbook ansible/prerequisites.yaml
ansible-playbook ansible/predestination-undo.yaml
ansible-playbook -l green ansible/dns.yaml
ansible all -m ping
