---
- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Create a user account for the application
      user:
        name: web
        shell: /bin/false
    - name: Create the application directory
      file:
        path: /var/www/predestination
        state: directory
        owner: web
        group: web
    - name: Clone the repository
      remote_user: web
      become: yes
      git:
        repo: https://github.com/SamirTalwar/predestination.git
        dest: /var/www/predestination
        version: error-prone
        update: yes
    - name: Install the application dependencies
      command: make site-packages
      args:
        chdir: /var/www/predestination
    - name: Set up the supervisor for the application
      copy:
        src: ../supervisor/predestination.conf
        dest: /etc/supervisor/conf.d/predestination.conf
    - name: Re-read the supervisor configuration
      command: supervisorctl reread
    - name: Restart the application
      supervisorctl:
        name: predestination
        state: restarted
    - name: Disable the default nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: Configure nginx to proxy Predestination
      copy:
        src: ../nginx/predestination.conf
        dest: /etc/nginx/sites-available/predestination.conf
    - name: Enable the nginx proxy
      file:
        src: /etc/nginx/sites-available/predestination.conf
        dest: /etc/nginx/sites-enabled/predestination.conf
        state: link
    - name: Reload the nginx configuration
      service:
        name: nginx
        state: reloaded
