---
- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Run the application in Docker
      docker_container:
        name: predestination
        image: samirtalwar/predestination
        pull: yes
        published_ports:
          - 80:8080
        restart_policy: on-failure
    - name: Update the DNS to the given cluster
      cloudflare_dns:
        zone: "{{ domain }}"
        record: "{{ subdomain }}"
        type: A
        value: "{{ inventory_hostname }}"
        account_email: "{{ cloudflare_email }}"
        account_api_token: "{{ cloudflare_token }}"
        proxied: true
        solo: true
