---
- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Remove the application from the supervisor
      file:
        path: /etc/supervisor/conf.d/predestination.conf
        state: absent
    - name: Re-read the supervisor configuration
      command: supervisorctl reread
    - name: Update the supervisor
      command: supervisorctl update
    - name: Stop forwarding port 80 to port 8080
      file:
        path: /etc/nginx/sites-enabled/predestination.conf
        state: absent
    - name: Delete the Nginx configuration
      file:
        path: /etc/nginx/sites-available/predestination.conf
        state: absent
    - name: Reload the nginx configuration
      service:
        name: nginx
        state: reloaded
    - name: Wait for the application to stop
      wait_for:
        host: localhost
        port: 8080
        state: drained
    - name: Remove the application directory
      file:
        path: /var/www/predestination
        state: absent
    - name: Remove the other application directory
      file:
        path: /home/ubuntu/predestination
        state: absent
    - name: Remove the application user account
      user:
        name: web
        shell: /bin/false
        state: absent
