---
- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Run the application in Docker
      docker_container:
        name: predestination
        image: samirtalwar/predestination
        pull: yes
        published_ports:
          - 80:8080
        restart_policy:  on-failure
