---
- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Run the application in Docker
      docker_container:
        name: predestination
        image: samirtalwar/predestination
        pull: yes
        published_ports:
          - 80:8080
        restart_policy: on-failure
    - name: Wait for the application to start
      wait_for:
        host: localhost
        port: 80

- import_playbook: dns.yaml
